language: r
sudo: false
cache: packages

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
 - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: BH89TWt2sC+iF+j3uq0VhQ8weYKhi6/vgOU4Xu4fRnXFb37+lW9F7xI1LzBwhCFe2mri1b8bFF1IV1mFq6NVdkOHLg1/CF7J2C106yMO56zj8qes4KwZ7YHdU2shzYUKovi7uoDyGlUzsAYpKEe2VbL2bSMUQtdBh2nbI47CCu0=
